language: python
sudo: false
python:
- '2.7'
addons:
  apt:
    packages:
      - python-psycopg2
      - python-pywcs
      - python-matplotlib
      - python-numpy
      - python-scipy
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
script:
  - touch project/settings/local.py
  - ./manage.py test --settings=testing.settings
branches:
  only:
    - master
notifications:
  hipchat:
    rooms:
      secure: bIAqBl41man+FGmBulMMxa1vHHEI0GIGnkonEg8FyQTdySTkQ1tMjnILL33mCJMo+ziqo6FEVVpu2IfdxKgG024gl3HHnu0vxp6teTOWfg1KwUhEIIiHkRJNEcEAZxe2QXlfpO1bLraWECZeNTGeQw782/BqlHyZr+88T18rsuU=
