language: python
python:
  - '2.7'
before_install:
  - sudo apt-get install python-psycopg2 python-pywcs python-matplotlib python-numpy
  - pip install astropy
install:
  - pip install -r requirements.txt --use-mirrors
script:
  - touch project/settings/local.py
  - ./manage.py test --settings=testing.settings
branches:
  only:
    - master
notifications:
  hipchat:
    rooms:
      secure: GXQo2vgPmAY1WRuPDcASUz8uFWgVOH9sUX6Zo2OH24c1wYKFq6J3jDprbbjjowQSzOYbNHJ3knBq7kiPd0tBpc0JxC3IIykNynTGra80kJhuE2OuYgd65K7uRtXQ58NVN1kRuYiPziq/Kb8XIkrzFWHBWgEF4gUtttWKyVxCsYQ=

